# Generated by Django 4.0 on 2021-12-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_referencial',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagenes/', verbose_name='Imagen referencial'),
        ),
    ]
